### ISSUE TITLE
elasticsearch-index-util.service.js created in a not usual folder

### ISSUE THREAD

**Issue by marcelinobadin** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#11]
I have installed this plugin and once it creates this file, it creates in

``src/main/webapp/app/components/util/elasticsearch-index-util.service.js``

is not a better place the

``src/main/webapp/scripts/components/util/elasticsearch-index-util.service.js``

**Comment by geraldhumphries** [comment]
Whoa, not sure how that snuck into the last release. If was unfinished and JHipster has gone through several major breaking changes (including the folders being reorganized) since I last worked on it. I'm re-releasing without that file, and I'll look into adding it again after.
