### ISSUE TITLE
adding angular module with wrong name

### ISSUE THREAD

**Issue by marcelinobadin** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#12]
in the js component it is gettting the name of the module and adding 'App' as a suffix but the module name already has the App added by Jhipster Generator. So once you try to test you got an error.

**Comment by geraldhumphries** [comment]
Hi, what version of JHipster are you using?

**Comment by geraldhumphries** [comment]
Same story as #11, this was an unfinished file that I accidentally included in 0.0.7.
