### ISSUE TITLE
Problem with the injecting reindexer into the navbar in the JH4

### ISSUE THREAD

**Issue by AntonLem** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#24]
During the composing of configuration in the JH4 the issue is occuring

> Unable to find src/main/webapp/app/layouts/navbar/navbar.component.html or missing required jhipster-needle. Reference to elasticsearch-reindex not added to in menu.

But
`src\main\webapp\app\layouts\navbar\navbar.html` is on the its place
and the comment
`<!-- jhipster-needle-add-element-to-admin-menu - JHipster will add entities to the admin menu here -->` is present too

**Comment by geraldhumphries** [comment]
Sorry about the delay.

It looks like JHipster is specifically looking for navbar.**component**.html. Are you using a different version of JHipster than you used to generate your app?

**Comment by AntonLem** [comment]
I'm not. Absolutely identical version JH4.1.1

**Comment by geraldhumphries** [comment]
JHipster's module API changed so a lot of functions now require you to pass in clientFramework. Without it, it defaults to Angular 2. The navbar.components.html file exists in Angular 2 apps but not Angular 1.

I've pushed the fix to master and will be releasing it soon.

**Comment by AntonLem** [comment]
Very well! Thanks a lot!
