### ISSUE TITLE
Bug: elasticsearch-reindex not found

### ISSUE THREAD

**Issue by alyssonmessias** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#27]
After _install generator-jhipster-elasticsearch-reindexer_ "**yo jhipster-elasticsearch-reindexer**" this file "index.html" not is alter how seen in image below:

![image](https://user-images.githubusercontent.com/7686638/26843977-5a9dc168-4ac8-11e7-80cd-e4818affcffb.png)

For fix this bug, must be include this lines in file "index.html" how that example:

_<script src="app/admin/elasticsearch-reindex/elasticsearch-reindex-dialog.controller.js"></script>_
_<script src="app/admin/elasticsearch-reindex/elasticsearch-reindex.controller.js"></script>_
_<script src="app/admin/elasticsearch-reindex/elasticsearch-reindex.service.js"></script>_
_<script src="app/admin/elasticsearch-reindex/elasticsearch-reindex.state.js"></script>_

After changes this module will work perfect.

![image](https://user-images.githubusercontent.com/7686638/26844344-7a68a87c-4ac9-11e7-9212-ac92227765b1.png)

**Comment by geraldhumphries** [comment]
Are you running gulp? It should be automatically injecting the front end files for you.

**Comment by alyssonmessias** [comment]
I was follow steps the page oficial of JHispter: 

[https://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-elasticsearch-reindexer](https://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-elasticsearch-reindexer)

And didn't inject automatically code in front end. I has implemented the changes above.

**Comment by geraldhumphries** [comment]
Since you are using Angular 1, you need to be using gulp for the front-end files to be injected into your index.html automatically. Refer to the development guide here: https://jhipster.github.io/development/

**Comment by alyssonmessias** [comment]
I'll check it out. 

Thanks

**Comment by geraldhumphries** [comment]
Any luck?

**Comment by alyssonmessias** [comment]
Yes, worked good. Thanks for explanation.
