### ISSUE TITLE
ERROR in [at-loader] ./src/main/webapp/app/entities/region-s/region-s-delete-dialog.component.ts:58:23

### ISSUE THREAD

**Issue by jnuc093** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#33]
with jh 4.6.2

➜  blog jhipster import-jdl ~/Downloads/jhipster-jdl.jh
Executing jhipster:import-jdl /Users/qk/Downloads/jhipster-jdl.jh
The jdl is being parsed.
Writing entity JSON files.
Generating entities.

Found the .jhipster/RegionS.json configuration file, entity can be automatically generated!

The entity RegionS is being updated.

   create src/main/resources/config/liquibase/changelog/20170913062135_added_entity_RegionS.xml
   create src/main/java/com/sgcc/pms/domain/RegionS.java
   create src/main/java/com/sgcc/pms/repository/RegionSRepository.java
   create src/main/java/com/sgcc/pms/web/rest/RegionSResource.java
   create src/main/java/com/sgcc/pms/repository/search/RegionSSearchRepository.java
   create src/test/java/com/sgcc/pms/web/rest/RegionSResourceIntTest.java
 conflict src/main/resources/config/liquibase/master.xml
? Overwrite src/main/resources/config/liquibase/master.xml? overwrite this and all others
    force src/main/resources/config/liquibase/master.xml
   create src/main/webapp/app/entities/region-s/region-s.component.html
   create src/main/webapp/app/entities/region-s/region-s-detail.component.html
   create src/main/webapp/app/entities/region-s/region-s-dialog.component.html
   create src/main/webapp/app/entities/region-s/region-s-delete-dialog.component.html
   create src/main/webapp/app/entities/region-s/index.ts
   create src/main/webapp/app/entities/region-s/region-s.module.ts
   create src/main/webapp/app/entities/region-s/region-s.route.ts
   create src/main/webapp/app/entities/region-s/region-s.model.ts
   create src/main/webapp/app/entities/region-s/region-s.component.ts
   create src/main/webapp/app/entities/region-s/region-s-dialog.component.ts
   create src/main/webapp/app/entities/region-s/region-s-delete-dialog.component.ts
   create src/main/webapp/app/entities/region-s/region-s-detail.component.ts
   create src/main/webapp/app/entities/region-s/region-s.service.ts
   create src/main/webapp/app/entities/region-s/region-s-popup.service.ts
   create src/test/javascript/spec/app/entities/region-s/region-s-detail.component.spec.ts
    force src/main/webapp/app/entities/entity.module.ts
    force src/main/webapp/app/layouts/navbar/navbar.component.html
   create src/main/webapp/i18n/en/regionS.json
    force src/main/webapp/i18n/en/global.json

Running `webpack:build` to update client app

Execution complete
yarn run v0.27.5
$ yarn run cleanup && yarn run webpack:build:main
 10% building modules 1/4 modules 3 active ...rc/main/webapp/content/css/global.cssWarning: The 'no-use-before-declare' rule requires type infomation.

[at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from /Users/qk/myosgit/blog/tsconfig.json.

10029ms building modules
19ms sealing
0ms optimizing
0ms basic module optimization
21ms module optimization
0ms advanced module optimization
14ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
0ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
8ms module reviving
5ms module order optimization
9ms module id optimization
2ms chunk reviving
0ms chunk order optimization
15ms chunk id optimization
50ms hashing
1ms module assets processing
4737ms chunk assets processing
122ms additional chunk assets processing
1ms recording
0ms additional asset processing
0ms chunk asset optimization
 94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 3 errors
112ms asset optimization
Hash: 854143efe785237db7c7
Version: webpack 3.3.0
Time: 15186ms
[./node_modules/css-loader/index.js!./src/main/webapp/content/css/global.css] ./node_modules/css-loader!./src/main/webapp/content/css/global.css 4.8 kB {3} [built]
       [] -> factory:174ms building:2154ms = 2328ms
[./src/main/webapp/app/account/account.module.ts] ./src/main/webapp/app/account/account.module.ts 1.89 kB {1} [built]
       [] -> factory:376ms building:189ms dependencies:622ms = 1187ms
[./src/main/webapp/app/admin/admin.module.ts] ./src/main/webapp/app/admin/admin.module.ts 2.72 kB {1} [built]
       [] -> factory:376ms building:167ms dependencies:644ms = 1187ms
[./src/main/webapp/app/app.constants.ts] ./src/main/webapp/app/app.constants.ts 513 bytes {1} [built]
       [] -> factory:612ms building:69ms = 681ms
[./src/main/webapp/app/app.main.ts] ./src/main/webapp/app/app.main.ts 583 bytes {1} [built]
        factory:285ms building:2304ms = 2589ms
[./src/main/webapp/app/app.module.ts] ./src/main/webapp/app/app.module.ts 2.71 kB {1} [built]
       [] -> factory:85ms building:79ms = 164ms
[./src/main/webapp/app/blocks/config/prod.config.ts] ./src/main/webapp/app/blocks/config/prod.config.ts 391 bytes {1} [built]
       [] -> factory:88ms building:97ms dependencies:617ms = 802ms
[./src/main/webapp/app/blocks/config/uib-pagination.config.ts] ./src/main/webapp/app/blocks/config/uib-pagination.config.ts 1.5 kB {1} [built]
       [] -> factory:374ms building:95ms dependencies:169ms = 638ms
[./src/main/webapp/app/blocks/interceptor/http.provider.ts] ./src/main/webapp/app/blocks/interceptor/http.provider.ts 1.6 kB {1} [built]
       [] -> factory:378ms building:234ms dependencies:27ms = 639ms
[./src/main/webapp/app/entities/entity.module.ts] ./src/main/webapp/app/entities/entity.module.ts 1.36 kB {1} [built]
       [] -> factory:377ms building:210ms dependencies:51ms = 638ms
[./src/main/webapp/app/polyfills.ts] ./src/main/webapp/app/polyfills.ts 202 bytes {2} [built]
        factory:36ms building:2499ms = 2535ms
[./src/main/webapp/app/shared/index.ts] ./src/main/webapp/app/shared/index.ts 1.35 kB {1} [built]
       [] -> factory:623ms building:39ms = 662ms
[./src/main/webapp/app/vendor.ts] ./src/main/webapp/app/vendor.ts 283 bytes {1} [built]
       [] -> factory:25ms building:421ms = 446ms
[./src/main/webapp/content/css/global.css] ./src/main/webapp/content/css/global.css 1.05 kB {3} [built]
        factory:287ms building:29ms = 316ms
[./src/main/webapp/manifest.webapp] ./src/main/webapp/manifest.webapp 61 bytes {2} [built]
       [] -> factory:600ms dependencies:1ms building:584ms = 1185ms
    + 666 hidden modules

ERROR in [at-loader] ./src/main/webapp/app/entities/region-s/region-s-delete-dialog.component.ts:58:23
    TS2559: Type 'typeof RegionSDeleteDialogComponent' has no properties in common with type 'Component'.

ERROR in [at-loader] ./src/main/webapp/app/entities/region-s/region-s-dialog.component.ts:95:27
    TS2559: Type 'typeof RegionSDialogComponent' has no properties in common with type 'Component'.

ERROR in [at-loader] ./src/main/webapp/app/entities/region-s/region-s-dialog.component.ts:98:27
    TS2559: Type 'typeof RegionSDialogComponent' has no properties in common with type 'Component'.
error Command failed with exit code 2.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by geraldhumphries** [comment]
The errors are coming from `RegionSDeleteDialogComponent` and `RegionSDialogComponent`. I don't think this has anything to do with elasticsearch-reindexer.

If I am wrong, reopen with more information including code samples.
