### ISSUE TITLE
Compilation failure on microservices app

### ISSUE THREAD

**Issue by danielbrutti** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#42]
Hi,
I have created 3 microservices project. The UUA, a backend microservice and gateway.
I installed this package though 'yarn global add generator-jhipster-elasticsearch-reindexer', then executed on the 3 projects, these are the ouputs:

**OAuth2**
Welcome to the JHipster elasticsearch-reindexer generator! v1.1.0

WARNING no entities found
WARNING clientFramework is missing in JHipster configuration, using angular1 as fallback
WARNING angularAppName is missing in JHipster configuration, using baseName as fallback
identical src/main/java/com/cme/budderfly/authenticate/web/rest/ElasticsearchIndexResource.java
identical src/main/java/com/cme/budderfly/authenticate/service/ElasticsearchIndexService.java
End of elasticsearch-reindexer generator

**Microservice**
Welcome to the JHipster elasticsearch-reindexer generator! v1.1.0

ls: no such file or directory: .jhipster

WARNING no entities found
WARNING clientFramework is missing in JHipster configuration, using angular1 as fallback
WARNING angularAppName is missing in JHipster configuration, using baseName as fallback
   create src/main/java/com/cme/budderfly/management/web/rest/ElasticsearchIndexResource.java
   create src/main/java/com/cme/budderfly/management/service/ElasticsearchIndexService.java
   create .jhipster/modules/jhi-hooks.json
End of elasticsearch-reindexer generator

**Gateway**
Welcome to the JHipster elasticsearch-reindexer generator! v1.1.0

ls: no such file or directory: .jhipster

WARNING no entities found
   create src/main/java/com/cme/budderfly/management/gateway/web/rest/ElasticsearchIndexResource.java
   create src/main/java/com/cme/budderfly/management/gateway/service/ElasticsearchIndexService.java
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex-modal.component.html
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex-modal.component.ts
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.component.html
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.component.ts
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.module.ts
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.route.ts
   create src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.service.ts
   create src/main/webapp/app/admin/elasticsearch-reindex/index.ts
 conflict src/main/webapp/app/admin/admin.module.ts
? Overwrite src/main/webapp/app/admin/admin.module.ts? overwrite this and all others
    force src/main/webapp/app/admin/admin.module.ts
    force src/main/webapp/app/layouts/navbar/navbar.component.html
    force src/main/webapp/i18n/en/global.json
   create src/main/webapp/i18n/en/elasticsearch-reindex.json
   create .jhipster/modules/jhi-hooks.json
End of elasticsearch-reindexer generator

I can start OAuth2 and microservice apps without issues (./mvnw), but the gateway app is throwing this exception:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project managementgateway: Compilation failure: Compilation failure: 
[ERROR] /home/daniel/workspace/budderfly/budderfly.cloud/management.gateway/src/main/java/com/cme/budderfly/management/gateway/service/ElasticsearchIndexService.java:[40,19] cannot find symbol
[ERROR]   symbol:   class UserRepository
[ERROR]   location: class com.cme.budderfly.management.gateway.service.ElasticsearchIndexService
[ERROR] /home/daniel/workspace/budderfly/budderfly.cloud/management.gateway/src/main/java/com/cme/budderfly/management/gateway/service/ElasticsearchIndexService.java:[42,19] cannot find symbol
[ERROR]   symbol:   class UserSearchRepository
[ERROR]   location: class com.cme.budderfly.management.gateway.service.ElasticsearchIndexService
[ERROR] /home/daniel/workspace/budderfly/budderfly.cloud/management.gateway/src/main/java/com/cme/budderfly/management/gateway/service/ElasticsearchIndexService.java:[49,9] cannot find symbol
[ERROR]   symbol:   class UserRepository
[ERROR]   location: class com.cme.budderfly.management.gateway.service.ElasticsearchIndexService
[ERROR] /home/daniel/workspace/budderfly/budderfly.cloud/management.gateway/src/main/java/com/cme/budderfly/management/gateway/service/ElasticsearchIndexService.java:[50,9] cannot find symbol
[ERROR]   symbol:   class UserSearchRepository
[ERROR]   location: class com.cme.budderfly.management.gateway.service.ElasticsearchIndexService
[ERROR] -> [Help 1]

Can you please help? Thanks!

**Comment by geraldhumphries** [comment]
I will need to look into this. I do not have any microservice apps in JHipster so I haven't been keeping up to date. It was probably refactored.

Thanks for opening this issue.

**Comment by danielbrutti** [comment]
No problem... if I found the solution I will post it here. I think it might need to change on client side to do the call to backend microservice, then just remove classes from the java code for gateway microservice. I'll work on it tomorrow and let you know.

**Comment by ruddell** [comment]
This issue happens because a gateway using the UAA auth type doesn't contain the expected user entity.  The easiest fix would be to add the following in [here in index.js](https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer/blob/master/generators/app/index.js#L51):

```
      this.authenticationType = config.authenticationType;

      if (this.authenticationType === 'uaa' && this.applicationType === 'gateway') {
        this.skipUserManagement = true;
      }
```

**Comment by danielbrutti** [comment]
I got this working by doing the following:

1. As @ruddell said, the `ElasticsearchIndexResource` and `ElasticsearchIndexService` should not be created on gateway project. I delete them manually.
2. I edited `elasticsearch-reindex.service.ts` to be
```typescript
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Rx';

import { SERVER_API_URL } from '../../app.constants';

@Injectable()
export class ElasticsearchReindexService {

    private resourceUrl = SERVER_API_URL + 'management/api/elasticsearch/index';

    constructor(
      private http: HttpClient
    ) { }

    reindex(): Observable<HttpResponse<any>> {
        return this.http.post<any>(this.resourceUrl, { observe: 'response' });
    }
}
```

In the generator you should change this line to use the backend microservice name, in my case it was `management`, but you should change this by some variable value or maybe ask the user during generation.
```typescript
private resourceUrl = SERVER_API_URL + 'management/api/elasticsearch/index';
```

**Comment by ruddell** [comment]
It is possible to use ElasticSearch on the gateway, it's not normally recommended to have entities in a gateway but in JWT and OAuth2 gateways there is the User entity.   The problem with prompting for a service name is that there's no limit to the number of microservices you use with this module.

There's also no standard way to list microservice names.  Maybe looping through the entity JSON files and getting the unique microserviceNames would work.

**Comment by geraldhumphries** [comment]
Does the gateway know about all other services? Maybe the gateway could handle forwarding the request to each microservice.

**Comment by geraldhumphries** [comment]
I've fixed the compilation error caused by trying to index the non-existent User entity. Can you make sure it compiles?

I've left the server-side files for now.
