### ISSUE TITLE
Can't resolve '@angular/http' in Angular 5

### ISSUE THREAD

**Issue by danielbrutti** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#43]
The following javascript error is thrown with last version of JHipster,

```
ERROR in ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.service.ts
Module not found: Error: Can't resolve '@angular/http' in '/home/daniel/workspace/budderfly/budderfly.cloud/management.gateway/src/main/webapp/app/admin/elasticsearch-reindex'
 @ ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.service.ts 13:13-37
 @ ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex-modal.component.ts
 @ ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.component.ts
 @ ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.route.ts
 @ ./src/main/webapp/app/admin/elasticsearch-reindex/index.ts
 @ ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.module.ts
 @ ./src/main/webapp/app/admin/admin.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main

ERROR in [at-loader] ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.service.ts:2:32
```

I fixed it by changing ``elasticsearch-reindex.service.ts`` to the following in order to accomodate to Angular 5
```typescript
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Rx';

@Injectable()
export class ElasticsearchReindexService {

    constructor(
      private http: HttpClient
    ) { }

    reindex(): Observable<HttpResponse<any>> {
        return this.http.post<any>('api/elasticsearch/index', {});
    }
}
```

**Comment by geraldhumphries** [comment]
Code looks good, however the post request will need to have `{observe: 'response'}` in the config object to get an HttpResponse object.

The Yeoman generator will need to get some new logic to switch between Angular 2-4 and Angular 5. 

Side note: doesn't Angular 5 include a deprecated version of the previous HTTP API?

**Comment by ruddell** [comment]
@geraldhumphries Angular does have a deprecated package, but it was removed from the package.json ([in this commit](https://github.com/jhipster/generator-jhipster/commit/f83f10b6367bbb977be975a6f220dc5e3e0e2f51)) so it isn't available.  I don't think you can switch based on Angular versions (unless you parse the package.json) but the removal of `@angular/http` happened in v4.14.0 of `generator-jhipster`

**Comment by geraldhumphries** [comment]
I will probably use the JHipster version to determine the Angular version like I've been doing, but this of course is not perfect and will fail if someone upgraded Angular without upgrading JHipster. Parsing the package.json would be a better solution.

**Comment by danielbrutti** [comment]
Hi, thanks for the ``{observe: 'response'}`` note, I will do that change.

About the version, I'm not too familiar with Yarn yet.. but maybe you can use a command to know the Angular version for current project?
