### ISSUE TITLE
"...@angular/common/http" has no exported member 'Response' (nor 'Http')

### ISSUE THREAD

**Issue by bnts43** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#44]
When setting up Jhipster with elasticsearch and reindex, following error has shown:
`ERROR in [at-loader] ./src/main/webapp/app/admin/elasticsearch-reindex/elasticsearch-reindex.service.ts:2:10
    TS2305: Module '"c:/***/node_modules/@angular/common/http"' has no exported member 'Http'.`

I've changed the service file 'elasticsearch-reindex/elasticsearch-reindex.service.ts' to attached file due to Angular 5 on my project and 'http' deprecated has to be replaced with HttpClient

[elasticsearch-reindex.service.ts.zip](https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer/files/1871503/elasticsearch-reindex.service.ts.zip)

Not sure if it's right but it might help
regards

**Comment by ruddell** [comment]
I tested and can confirm, thanks for reporting.  [The import line](https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer/blob/master/generators/app/templates/src/main/webapp/ts/_elasticsearch-reindex.service.ts#L3) needs a change, as well as the constructor (line 13).

**Comment by geraldhumphries** [comment]
My mistake. Fix coming soon.

**Comment by geraldhumphries** [comment]
@bnts43 can you test out `master`? I will release if everything looks okay.

**Comment by bnts43** [comment]
just checked with `master` . all working fine. thanks!
