### ISSUE TITLE
Losing mapping

### ISSUE THREAD

**Issue by marquetd** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#9]
The index mapping is lost when calling the method "reindexAll".

Replace "deleteIndex" with "deleteAll" if searchRepository.count()>0

**Comment by geraldhumphries** [comment]
This is actually intentional - if the datatype of a field changes, the old mapping will cause errors when trying to index a new document.

I have not had a need to use explicit mapping, so I don't have any experience doing this - but try the Spring Data Elasticsearch mapping annotations in your entities. That way you don't need to run queries to define mappings and you won't lose your mappings when running `reindexAll`.

**Comment by marquetd** [comment]
Ok i understand the problem and your needs.

I already use annotations in my entities that why i'm quite surprised off the result.
To me, the mapping is very important to make a good search engine.

Thanks for your response.

**Comment by geraldhumphries** [comment]
The mappings you define in your annotations don't get applied? I will need to investigate this if that isn't working.

**Comment by marquetd** [comment]
That's it.

For the moment, to me, the workaround (for datatype changes or other important changes) is to delete the index outside the applicaiton (by queries,...)

Thanks for your job.

**Comment by geraldhumphries** [comment]
@marquetd, can you give me an example of a mapping that is not being applied, and an example of how you applied it in the first place?

**Comment by marquetd** [comment]
To apply it, i use the jhipster's generated implementation of entity, nothing more.

here is the code : 
```java
.....
@Entity
@Table(name = "person")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Document(indexName = "person")
public class Person implements Serializable {
....
    @MultiField(
            mainField = @Field(type = FieldType.String),
            otherFields = {
                @NestedField(
                        dotSuffix = "raw",
                        type = FieldType.String,
                        store = true,
                        index = FieldIndex.not_analyzed
                )
            }
    )
    @Size(max = 200)
    @Column(name = "town", length = 200)
    private String town;
```

**Comment by geraldhumphries** [comment]
Thanks, I'll look into it.

**Comment by geraldhumphries** [comment]
It should be properly applying the mapping now. I have noticed that the mapping doesn't get applied for the entity in a relationship - but that seems to match the default behaviour. I will double check.

**Comment by geraldhumphries** [comment]
Confirmed, it matches the default behaviour now. I will do a release soon.

**Comment by marquetd** [comment]
ok cool
